
spring:
  application:
    name: spring-cloud-consumer
  #是否允许一样的bean
  main:
    allow-bean-definition-overriding: true
server:
  port: 9003

#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    #是否注册服务
    #register-with-eureka: false

#熔断器
feign:
  hystrix:
    enabled: true